dataset_path: ???
scans_dir: scans
masks_dir: masks
allow_missing_scans: false
allow_missing_masks: false
task: null
feature_groups: null
caching_strategy: disk
cache_dir: null
enable_augmentations: true
