backbone: dinov2-small
freeze_backbone: true
pooling:
  dropout: 0.1
  return_attention: false
  use_rope: false
  rope_theta: 10000.0
classifier:
  num_hidden_layers: 1
  hidden_dim: 256
  dropout_rate: 0.1
  activation: gelu
