max_epochs: 50
lr: 1e-4
weight_decay: 1e-5
scheduler:
  name: cosine
  warmup_steps: 0
enable_checkpointing: true
enable_lr_monitor: true
early_stopping_monitor: val/loss
early_stopping_patience: 10
early_stopping_mode: min
checkpoint_monitor: val/auroc
checkpoint_mode: max
checkpoint_save_top_k: 1
